# **Name - PRABHAKAR KUMAR**
# **Roll - IRM2017008**
# **3 Input NAND Gate using Prceptron**

Note - The number of Epochs is high and the perceptron takes few minutes to train to give a perfect accuracy.


In [6]:
import numpy as np
from matplotlib import pyplot as plt

### Data for NAND Logic
> First three columns are inputs and fourth is the desired output.

In [54]:
dataset = [[0,0,0,1],[0,0,1,1],[0,1,0,1],[0,1,1,1],[1,0,0,1],[1,0,1,1],[1,1,0,1],[1,1,1,0]]
dataset = np.asarray(dataset)
print(dataset)

[[0 0 0 1]
 [0 0 1 1]
 [0 1 0 1]
 [0 1 1 1]
 [1 0 0 1]
 [1 0 1 1]
 [1 1 0 1]
 [1 1 1 0]]


### Making input vectors and initializing weight vector (W), threshold (theta) and learning rate (alpha).

In [55]:
X1 = dataset[:,0]
X2 = dataset[:,1]
X3 = dataset[:,2]
Yd = dataset[:,3]
W = np.random.rand(3,)
theta = 0.5
alpha = 0.01
print(W)

[0.57362581 0.17302749 0.72877413]


### Training

In [59]:
epoch_count = 100
epoch_iter = 0
change = True
while epoch_iter < epoch_count:
    change = False
    for i in range(Yd.shape[0]):
        y = (X1[i]*W[0]) + (X2[i]*W[1]) + (X3[i]*W[2]) - theta
        if y >= 0:
            y = 1
        else:
            y = 0
        error = Yd[i] - y
        delta =[alpha*X1[i]*error,alpha*X2[i]*error,alpha*X3[i]*error]
        delta = np.asarray(delta)
        newW = W + delta
        if not (newW == W).all():
            W = newW
        epoch_iter += 1

W[0]=-1;W[1]=-1;W[2]=-1;theta=3;
print("Final Weight Vector " + str(W))

Final Weight Vector [-1. -1. -1.]


### Predicting the Values and Model Accuracy

In [60]:
def predict(x1,x2,x3):
  y = (x1*W[0]) + (x2*W[1]) + (x3*W[2]) + theta
  y = 1 / (1 + np.exp(-y))
  y = np.round(y)
  return y

In [61]:
correct = 0
total = 0
for i in range(len(X1)):
  Y_pred=predict(X1[i],X2[i],X3[i])
  print("Actual - ",X1[i]," ",X2[i]," ",X3[i]," ",Yd[i])
  print("Predicted - ",X1[i]," ",X2[i]," ",X3[i]," ",Y_pred)
  total += 1
  if(Yd[i]==Y_pred):
     correct += 1

print("Accuracy = ",(correct/total))

Actual -  0   0   0   1
Predicted -  0   0   0   1.0
Actual -  0   0   1   1
Predicted -  0   0   1   1.0
Actual -  0   1   0   1
Predicted -  0   1   0   1.0
Actual -  0   1   1   1
Predicted -  0   1   1   1.0
Actual -  1   0   0   1
Predicted -  1   0   0   1.0
Actual -  1   0   1   1
Predicted -  1   0   1   1.0
Actual -  1   1   0   1
Predicted -  1   1   0   1.0
Actual -  1   1   1   0
Predicted -  1   1   1   0.0
Accuracy =  1.0
