# **Name - PRABHAKAR KUMAR**
# **Roll - IRM2017008**
# **Assignment 7 - KNN Algorithm**

## **Loading Dataset**

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.DataFrame(pd.read_csv('data.csv',delimiter=','))
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Value1  100 non-null    float64
 1   Value2  100 non-null    float64
 2   Class   100 non-null    int64  
dtypes: float64(2), int64(1)
memory usage: 2.5 KB


In [3]:
data.head()

Value1     Value2  Class
0  34.623660  78.024693      0
1  30.286711  43.894998      0
2  35.847409  72.902198      0
3  60.182599  86.308552      1
4  79.032736  75.344376      1

In [5]:
row_count = len(data.index)
print(row_count)

100


In [7]:
trainSet = data[30:60]
testSet = data[90:]

## **Creating Training and Testing Dataset**

In [11]:
x_train=trainSet[['Value1','Value2']].values
y_train=trainSet['Class'].values
x_test=testSet[['Value1','Value2']].values
y_test=testSet['Class'].values

In [12]:
print(x_test)

[[94.09433113 77.15910509]
 [90.44855097 87.50879176]
 [55.48216114 35.57070347]
 [74.49269242 84.84513685]
 [89.84580671 45.35828361]
 [83.48916274 48.3802858 ]
 [42.26170081 87.10385094]
 [99.31500881 68.77540947]
 [55.34001756 64.93193801]
 [74.775893   89.5298129 ]]


In [13]:
print(y_test)

[1 1 0 1 1 1 1 1 1 1]


In [16]:
print(y_train[0])

1


# **K = 3**

## **Regression + Classification with KNN**

In [17]:
# K Parameter
K=3

n=len(y_train)
count=len(y_test)
regression_prediction = []
classification_prediction = []

for i in range(count):
  distance=[]
  for j in range(n):
    dist=np.power((x_test[i][0]-x_train[j][0]),2)+np.power((x_test[i][1]-x_train[j][1]),2)
    distance.append([dist,j])
  distance.sort()
  sum=0
  for j in range(K):
    sum += y_train[distance[j][1]]
  sum = sum/K
  regression_prediction.append(sum)
  if(sum>=0.5):
    classification_prediction.append(1)
  else:
    classification_prediction.append(0)

In [18]:
print(classification_prediction)

[1, 1, 0, 1, 1, 1, 0, 1, 0, 1]


In [19]:
print(y_test)

[1 1 0 1 1 1 1 1 1 1]


## **Classification Accuracy**



In [20]:
correct = 0

for i in range(count):
  if(classification_prediction[i]==y_test[i]):
    correct += 1

accuracy = correct / count
print("Classification Accuracy = ",accuracy)

Classification Accuracy =  0.8


## **Regression Accuracy**

In [21]:
print(regression_prediction)

[1.0, 1.0, 0.0, 1.0, 0.6666666666666666, 0.6666666666666666, 0.0, 1.0, 0.3333333333333333, 1.0]


In [23]:
squared_error = 0

for i in range(count):
  temp = np.power((regression_prediction[i]-y_test[i]),2)
  squared_error += temp

print("Squared Error in Regression - ",squared_error);

Squared Error in Regression -  1.666666666666667


# **K = 5**

## **Regression + Classification with KNN**

In [24]:
# K Parameter
K=5

n=len(y_train)
count=len(y_test)
regression_prediction = []
classification_prediction = []

for i in range(count):
  distance=[]
  for j in range(n):
    dist=np.power((x_test[i][0]-x_train[j][0]),2)+np.power((x_test[i][1]-x_train[j][1]),2)
    distance.append([dist,j])
  distance.sort()
  sum=0
  for j in range(K):
    sum += y_train[distance[j][1]]
  sum = sum/K
  regression_prediction.append(sum)
  if(sum>=0.5):
    classification_prediction.append(1)
  else:
    classification_prediction.append(0)

## **Classification Accuracy**



In [25]:
correct = 0

for i in range(count):
  if(classification_prediction[i]==y_test[i]):
    correct += 1

accuracy = correct / count
print("Classification Accuracy = ",accuracy)

Classification Accuracy =  0.8


## **Regression Accuracy**

In [26]:
squared_error = 0

for i in range(count):
  temp = np.power((regression_prediction[i]-y_test[i]),2)
  squared_error += temp

print("Squared Error in Regression - ",squared_error);

Squared Error in Regression -  1.3200000000000003
