# **Name - PRABHAKAR KUMAR**
# **Roll - IRM2017008**
# **Assignment 8 - Bidirectional Associative Memory**

In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt

# **Preparing the Given Data for BAM**

In [2]:
A = [[1,1,1,1,1,1],[-1,-1,-1,-1,-1,-1],[1,-1,-1,1,1,1],[1,1,-1,-1,-1,-1]]
A = np.asarray(A)

In [3]:
print(A)

[[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [ 1 -1 -1  1  1  1]
 [ 1  1 -1 -1 -1 -1]]


In [4]:
B = [[1,1,1],[-1,-1,-1],[-1,1,1],[1,-1,1]]
B = np.asarray(B)

In [5]:
print(B)

[[ 1  1  1]
 [-1 -1 -1]
 [-1  1  1]
 [ 1 -1  1]]


In [6]:
W = np.zeros((A[0].shape[0],B[0].shape[0]))

In [7]:
print(W)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
for i in range(A.shape[0]):
    X = A[i].reshape(A[i].shape[0],1)
    Y = B[i].reshape(B[i].shape[0],1)
    W += np.matmul(X,Y.T)

In [9]:
print(W)

[[2. 2. 4.]
 [4. 0. 2.]
 [2. 2. 0.]
 [0. 4. 2.]
 [0. 4. 2.]
 [0. 4. 2.]]


# **Validation of the Weight Matrix**

In [11]:
count = 2*(A.shape[0])

for i in range(A.shape[0]):
    X = A[i].reshape(A[i].shape[0],1)
    Y = B[i].reshape(B[i].shape[0],1)
    
    Y_pred = np.matmul(W.T,X)
    Y_pred = Y_pred.reshape(Y_pred.shape[0],)
    for j in range(Y_pred.shape[0]):
        if Y_pred[j] < 0:
            Y_pred[j] = -1
        elif Y_pred[j] >= 0:
            Y_pred[j] = 1
    Y_pred = Y_pred.reshape(Y_pred.shape[0],1)
    
    X_pred = np.matmul(W,Y)
    X_pred = X_pred.reshape(X_pred.shape[0],)
    for j in range(X_pred.shape[0]):
        if X_pred[j] <= 0:
            X_pred[j] = -1
        elif X_pred[j] > 0:
            X_pred[j] = 1
    X_pred = X_pred.reshape(X_pred.shape[0],1)
    
    if (Y_pred==Y).all():
        count -=1
    else:
        print("X"+str(i+1)+" fails to recall Y"+str(i+1))
        break
    
    if (X_pred==X).all():
        count -=1
    else:
        print("Y"+str(i+1)+" fails to recall X"+str(i+1))
        break

if count == 0:
    print("All pairs correctly associated.\nTesting Result: Successful")
else:
    print("Testing Result: Failed")

All pairs correctly associated.
Testing Result: Successful


In [12]:
print("Weight Matrix Mapping X's to Y's : ")
print(W)

Weight Matrix Mapping X's to Y's : 
[[2. 2. 4.]
 [4. 0. 2.]
 [2. 2. 0.]
 [0. 4. 2.]
 [0. 4. 2.]
 [0. 4. 2.]]


# **Example of Weight Correction by BAM**

In [13]:
# corrupted version of X1 (changing 1st bit)
givenX = [-1,1,1,1,1,1]
givenX = np.asarray(givenX)

In [14]:
oldX = givenX.reshape(givenX.shape[0],1)
retrivedX = oldX
i = 0

while i==0 or (oldX!=retrivedX).any():
    oldX = retrivedX
    i+=1
    tempY = np.matmul(W.T,oldX)
    tempY = tempY.reshape(tempY.shape[0],)
    for j in range(tempY.shape[0]):
        if tempY[j] < 0:
            tempY[j] = -1
        elif tempY[j] >= 0:
            tempY[j] = 1
    tempY = tempY.reshape(tempY.shape[0],1)
    
    retrivedX = np.matmul(W,tempY)
    retrivedX = retrivedX.reshape(retrivedX.shape[0],)
    for j in range(retrivedX.shape[0]):
        if retrivedX[j] <= 0:
            retrivedX[j] = -1
        elif retrivedX[j] > 0:
            retrivedX[j] = 1
    retrivedX = retrivedX.reshape(retrivedX.shape[0],1)

retrivedX = np.asarray(retrivedX,dtype=int)
print("Corrupted Pattern")
print(givenX)
print("Retrived Pattern")
print(retrivedX.reshape(retrivedX.shape[0],))
print("Iterations taken: "+str(i))

Corrupted Pattern
[-1  1  1  1  1  1]
Retrived Pattern
[1 1 1 1 1 1]
Iterations taken: 2
